#!/bin/bash

echo "Bor stats:"

current_block=$(curl 'localhost:8545/' --header 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 2>/dev/null | jq -M -r .result.currentBlock | sed -e 's/^0x//g' | while read x ; do  echo $(( 16#$x ))  ; done)
echo " Current Block: $current_block"

peers=$(curl -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "net_peerCount", "params": [], "id": 74}' localhost:8545 2>/dev/null | jq -M -r .result | sed -e 's/^0x//g' | while read x ; do  echo $(( 16#$x ))  ; done  )
echo " Peers: $peers"
